version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "./dockercompose/mongo/:/data/db"
    ports:
      - "27017:27017"
    networks:
      - sa-network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sa-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - sa-network 
networks:
  sa-network:
    name: sa-network
    driver: bridge
  rabbitmq_go_net:
    name: rabbitmq_go_net
    driver: bridge
