mail_alert_recipients: ["alejogaratd@gmail", "juanpeds00@gmail.com"]
mail_open_certificate_recipients: ["alejogaratd@gmail", "juanpeds00@gmail.com"]
mail_close_certificate_recipients: ["alejogaratd@gmail", "juanpeds00@gmail.com"]